name: Non-Stop YT Multi-IP Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein naya batch

jobs:
  viewer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 20 Parallel Watchers (Max for Free Tier)
        id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Watching Job
      env:
        STREAM_ID: ${{ secrets.STREAM_ID }}
        VIEWER_ID: Watcher-${{ matrix.id }} # Sirf logs mein identifying ke liye
      run: python watch.py
      
